# -*- coding: utf-8 -*-
"""Heart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VQxivZdNFxvns7euQs3CTUlG6pfdeB_A
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files
up=files.upload()

df=pd.read_csv('heart.csv')
df

df.info()

x=df.iloc[:,0:13]
y=df.iloc[:,13]
type(x)

'''from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size = .30, random_state = 0)
y_test'''

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression ()
lr.fit (x, y)

from sklearn.metrics import accuracy_score

data = [[int(input('Enter age: ')),int(input('Enter sex(Male-1/Female-0): ')),int(input('Enter chest pain type: ')),int(input('Enter rest BP : ')),int(input('Enter cholestrol: ')),int(input('Enter sugar: ')),int(input('Enter rest ecg: ')),int(input('Enter highest heart rate: ')),int(input('Enter exng: ')),float(input('Enter old peak: ')),int(input('Enter slp: ')),int(input('Enter Cerebral amyloid angiopathy: ')),int(input('Enter Thalassemia : '))]]
test= pd.DataFrame(data, columns=['age', 'sex','cp','trtbps','chol','fbs','restecg','thalachh','exng','oldpeak','slp','caa','thall'])
prediction = lr.predict (test)
print('SAFE')if prediction==1 else print('Treatment Required')