# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15li2NjaWCl1Wnd2_Xfvxk-n34f0fvsrV
"""

from distutils.log import debug
import numpy as np
from flask import Flask, request, render_template
import pickle

app = Flask(__name__)
model = pickle.load(open('/content/heart-disease.pkl','rb'))

@app.route("/home")
def home():
  return render_template("index.html")


@app.route("/predict",methods = ["POST"])
def predict():

  int_features = [int(x) for x in request.form.values()]
  final_features = [np.array(int_features)]
  prediction = model.predict(final_features)

  output = prediction[0]

  HeartDisease = ["You are Fine","You need Treatment. Kindly Consult a doctor."]

  return render_template(
      "index.html",prediction_text = "Result : {}".format(HeartDisease[output])
  )


__name__ == "__main__":
  app.run(debug=True)